# Generated by Django 5.2.4 on 2025-07-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='blog/images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
